### ISSUE TITLE
Regarding XmediaNet dataset

### ISSUE THREAD

**Issue by shivangibithel** [penghu-cs/DCHN#1]
Hey @penghu-cs 

Can you please share the feature matrix used to compute the results of xmedia and xmedianet dataset? 

Thanks in advance!

Shivangi Bithel

**Comment by penghu-cs** [comment]
Dear Shivangi Bithel,

Thanks a lot for your attention. The features could be obtained from the authors. The official website is: http://59.108.48.34/tiki/XMediaNet/ .

Best regards,
Peng Hu

**Comment by shivangibithel** [comment]
Thank you sir. I got the features. 

Best Regards,
Shivangi Bithel
